name: CMake Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.2.3'
        arch: 'win64_msvc2019_64'

    - name: Add CMake to PATH
      uses: lukka/get-cmake@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="D:/a/MHY_Scanner/Qt/6.2.3/msvc2019_64"

    - name: Build with MSBuild
      run: cmake --build build --config Release
